spring:
  datasource:
    url: 'jdbc:mysql://127.0.0.1:13307'
    password: root
    username: root
mybatis:
  config-location: 'classpath:mybatis/mybatis-config.xml'
  mapper-locations: 'classpath:mybatis/mapper/*.xml'

org:
  fenrir:
    mybatis:
      demo:
        simple: false #最簡的simple code demo
        page-select: true # demo for page select (分頁查詢)